DROP TABLE IF EXISTS purchases;
create table purchases
(
    id               bigint generated by default as identity,
    inner_id         varchar(255),
    marketplace_code varchar(255),
    ozon_id          varchar(255),
    price            varchar(255),
    purchase_date    varchar(255),
    purchase_name    varchar(255),
    region           varchar(255),
    website_id       varchar(255),
    wildberries_id   varchar(255),
    yandex_id        varchar(255),
    status        varchar(255),
    primary key (id)
);

DROP TABLE IF EXISTS uers;
create table users
(
    id               bigint generated by default as identity,
    name         varchar(255),
    password varchar(255),
    primary key (id)
);